name: Build Docker image

on:
  workflow_dispatch:
  push:

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Lint with flake8
  #     run: |
  #       # stop the build if there are Python syntax errors or undefined names
  #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  #       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build_docker_image:
    name: Docker Build
    runs-on: ubuntu-22.04
    # needs:
    #   - lint
    steps:
      - name: Publishing info
        run: |
          echo "Pushing docker image: ghcr.io/hickey/supernode:$GITHUB_REF_NAME"
          echo "Pushing docker image: ghcr.io/hickey/supernode:$GITHUB_SHA"
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Auth to GitHub registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [[ ${{ github.ref }} == 'refs/tags/'* ]]; then
          echo "DOCKER_TAG=$(echo ${{ github.ref }} | sed 's#refs/tags/##')" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hickey/supernode:${{ env.DOCKER_TAG }}
            ghcr.io/hickey/supernode:${{ github.sha }}